export const GET_ERRORS = 'GET_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SET_UPLOAD_PROGRESS = 'SET_UPLOAD_PROGRESS';
export const START_LOADING = 'START_LOADING';
export const STOP_LOADING = 'STOP_LOADING';
export const SET_QUESTIONS = 'SET_QUESTIONS';
export const CLEAR_QUESTIONS = 'CLEAR_QUESTIONS';
